### ISSUE TITLE
How to use this ? any spring boot example ? to use remote JBoss/infinispan ? will it work with JBoss/infinispan 9.4?

### ISSUE THREAD

**Issue by madhupnvl** [infinispan/infinispan-cachestore-cassandra#20]
Need a spring boot example to use this.

How to use this ? any spring boot example ? to use remote JBoss/infinispan ? will it work with JBoss/infinispan 9.4?

**Comment by galderz** [comment]
I'm not aware of spring boot examples on this, but the documentation on using this is [here](https://github.com/infinispan/infinispan-cachestore-cassandra/blob/master/documentation/src/main/asciidoc/index.adoc).
