### ISSUE TITLE
Tag and release 13.0.10.Final

### ISSUE THREAD

**Issue by dominikschlosser** [infinispan/infinispan-cachestore-cassandra#33]
@tristantarrant @jabolina In order to use the newly updated version of this cache-store, it would be nice if you tagged and released a new version. 

Preferrably to a public maven-repository as well.

Thank you!

**Comment by jabolina** [comment]
Created #34, and once merged, I'll release a 13.0.10.Final version.

**Comment by jabolina** [comment]
Took more than that PR in the end :sweat_smile:. @dominikschlosser should have `13.0.10.Final` available.

**Comment by dominikschlosser** [comment]
> Took more than that PR in the end 😅. @dominikschlosser should have `13.0.10.Final` available.

Great, thank you very much!
